version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php-app
    container_name: php-app
    environment:
      - DB_HOST=db
      - DB_NAME=blog
      - DB_USER=blog_user
      - DB_PASS=blog_user_secret
      - DB_PORT=3306
    volumes:
      - ./:/var/www
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-server
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    command: ["/bin/sh", "-c", "/var/www/wait-for-it.sh app:9000 -- nginx -g 'daemon off;'"]
    networks:
      - app-network

  db:
    image: mysql:8.3.0
    container_name: db
    environment:
      MYSQL_DATABASE: 'blog'
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_USER: 'blog_user'
      MYSQL_PASSWORD: 'blog_user_secret'
    volumes:
      - mysqldata:/var/lib/mysql
    restart: always
    ports:
      - "3309:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysqldata:
